# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mdui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1110, 836)
        self.title = QtWidgets.QLabel(Dialog)
        self.title.setGeometry(QtCore.QRect(30, 140, 1061, 191))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.go = QtWidgets.QPushButton(Dialog)
        self.go.setGeometry(QtCore.QRect(200, 520, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.go.setFont(font)
        self.go.setObjectName("go")
        self.go_2 = QtWidgets.QPushButton(Dialog)
        self.go_2.setGeometry(QtCore.QRect(660, 520, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.go_2.setFont(font)
        self.go_2.setObjectName("go_2")

        self.retranslateUi(Dialog)
        self.go.clicked.connect(Dialog.goin) # type: ignore
        self.go_2.clicked.connect(Dialog.goin1) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title.setText(_translate("Dialog", "欢迎进入高速公路车辆检测和识别系统"))
        self.go.setText(_translate("Dialog", "车辆检测"))
        self.go_2.setText(_translate("Dialog", "车型识别"))
