# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mfui1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog1(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1054, 824)
        self.detectButton = QtWidgets.QPushButton(Dialog)
        self.detectButton.setGeometry(QtCore.QRect(50, 50, 120, 30))
        self.detectButton.setObjectName("detectButton")
        self.detectButton.setText("识别车型")

        self.title = QtWidgets.QLabel(Dialog)
        self.title.setGeometry(QtCore.QRect(140, 50, 631, 41))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.video1 = QtWidgets.QLabel(Dialog)
        self.video1.setGeometry(QtCore.QRect(40, 110, 931, 521))
        self.video1.setObjectName("video1")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(70, 700, 251, 61))
        self.label.setObjectName("label")
        self.cardata = QtWidgets.QLabel(Dialog)
        self.cardata.setGeometry(QtCore.QRect(391, 680, 561, 91))
        self.cardata.setObjectName("cardata")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title.setText(_translate("Dialog", "车型识别"))
        self.video1.setText(_translate("Dialog", "shipin"))
        self.label.setText(_translate("Dialog", "车辆信息"))
        self.cardata.setText(_translate("Dialog", "TextLabel"))
