# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mfui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1097, 826)
        self.title = QtWidgets.QLabel(Dialog)
        self.title.setGeometry(QtCore.QRect(220, 40, 631, 41))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 100, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.carnum = QtWidgets.QLabel(Dialog)
        self.carnum.setGeometry(QtCore.QRect(190, 100, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.carnum.setFont(font)
        self.carnum.setStyleSheet("color:red\n"
"")
        self.carnum.setObjectName("carnum")
        self.video1 = QtWidgets.QLabel(Dialog)
        self.video1.setGeometry(QtCore.QRect(70, 170, 951, 591))
        self.video1.setObjectName("video1")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title.setText(_translate("Dialog", "车辆检测"))
        self.label.setText(_translate("Dialog", "车流量："))
        self.carnum.setText(_translate("Dialog", "0"))
        self.video1.setText(_translate("Dialog", "video"))
